apiVersion: v1
kind: Pod
metadata:
  name: fortio-master
  labels:
    name: fortio-master
spec:
  containers:
  - name: fortio
    image: fortio/fortio:latest_release
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
      name: http-fortio
    - containerPort: 8079
      name: grpc-ping
  nodeName: master
