apiVersion: v1
kind: Pod
metadata:
  name: fortio-node
  labels:
    name: fortio-node
spec:
  containers:
  - name: fortio
    image: fortio/fortio:latest_release
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
      hostPort: 8081
      name: http-fortio
    - containerPort: 8079
      hostPort: 8078
      name: grpc-ping
  nodeName: node
